CREATE TABLE "roles" (
    "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100)
);

CREATE TABLE "users" (
    "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(250) NOT NULL,
    "email" VARCHAR(250) UNIQUE,
    "password" VARCHAR(100),
    "role_id" INT,
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE "products" (
    "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(250) NOT NULL,
    "price" DECIMAL(10, 2) NOT NULL CHECK ("price" > 0),
    "stock" INT,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "description" TEXT
);

CREATE TABLE "orders" (
    "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT,
    "total_price" DECIMAL(10, 2),
    "created_at" TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE "order_items" (
    "id_order_item" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" INT,
    "product_id" INT,
    "quantity" INT,
    "price_at_order" DECIMAL (10, 2),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);